# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'SmartGarden' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartGarden

  pod 'Alamofire', '~> 4.8.2'

  
end
